### ISSUE TITLE
Support for 1.9

### ISSUE THREAD

**Issue by doylejg** [rom1504/MinecraftChat#4]
Hey Guys, 
Just wondering if you intend to continue support after the upgrade to Minecraft 1.9? Since the pre-releases have been pushed you can likely start testing. 
Jon

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol supports 1.9, but mineflayer hasn't been updated yet, so 1.9 support isn't possible here for now.
